name: bcrypt
description: This package use jBCrypt modified code to work with Dart VM.
version: 1.1.4
repository: https://github.com/astudilloalex/dart-bcrypt
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <3.11.0'
  
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.28.0
